name: Build

on:
  merge_group:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
        cache: 'maven'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
    - name: Build with Maven
      timeout-minutes: 15
      run: mvn -B clean javadoc:javadoc package --file pom.xml
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:java"